### ISSUE TITLE
Why is the image I generate an all-white image with no black font？

### ISSUE THREAD

**Issue by Chyamble** [ligoudaner377/font_translator_gan#15]
Hi, I've been trying to revive this project recently. I used the dataset provided by you and followed the parameters set in your paper
 --epoch=20, λ1 = 100, λc = λs = 1, --max_dataset_size= 6, and the result generated an all-white image without black font. I have searched for a long time but have not found any problem, I would like to ask the reason.

**Comment by ligoudaner377** [comment]
Hi, have you tried the default parameters for training & testing?
Just run ```script.sh```, which we provide.

**Comment by Chyamble** [comment]
Due to insufficient computing power of the graphics card, the previous problem occurred. Now I have realized the data in the paper, thank you for your reply。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月23日(星期四) 中午12:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ligoudaner377/font_translator_gan] Why is the image I generate an all-white image with no black font？ (Issue #15)





 
Hi, have you tried the default parameters for training &amp; testing?
 Just run script.sh, which we provide.
