### ISSUE TITLE
Is the layer attention layer implementation correct?

### ISSUE THREAD

**Issue by sunggukcha** [ligoudaner377/font_translator_gan#2]
Hello Li, we appreciate your contribution to the community.

I doubt the implementation of `layer_attn`. Compared to the illustrated layer attention in the paper, the following implementation does not handle any infomation from `style_feature_3 (feature vector 3 in the paper)`.

https://github.com/ligoudaner377/font_translator_gan/blob/master/models/networks.py#L926

Please check if the implementation is correct.

Regards,
Sungguk Cha

**Comment by ligoudaner377** [comment]
Hi, @sunggukcha !
Thank you for your interest in the project.
I checked the code and you are correct, that's an implementation error during the copy-paste.
I have already fixed it. 

Best regrads,
Chenhao Li
